### ISSUE TITLE
Testing a list of words

### ISSUE THREAD

**Issue by rboothneu** [LauraO6345/Week3-6345#1]
https://github.com/LauraO6345/Week3-6345/blob/80a05b7fa82bddd510e30866b6d54a6ff0ad631f/Ch6Exercises.py#L45

@LauraO6345  - Another feature of GitHub is that I can submit issues to your repo, calling out specific lines of code (or just describing a problem, or something to work on), and submit it. Then you can make commits that address it (or not) and then close it. This is a great way to collaborate and track changes.

For example, I could ask you to change the code to check through this list:
checkwords = ['bob','sandy','apple','kayak','elephant','racecar']

**Comment by LauraO6345** [comment]
Per GIS 6345 Week 3 assignment comment: Branch created and code added! (And I am closing this with this comment.)
